[inference]
    save_path = '/home/pl/projects/pl/MWT/results/{VIDEO_ID}.machine.pkl'  # {VIDEO_ID} will be auto-replaced

    [inference.classifier]
    evaluate = true
    force_dlc = false
    force_xgb = false

    [inference.classifier.models]
        xgb_model_path = "/home/pl/projects/pl//MWT/models/xgb.save"
        dlc_config_path = "/home/pl/projects/pl/DLC/Retraining-BenR-2020-05-25/config.yaml"

    [inference.cluster]
    evaluate = true
    force = false
    eps = 10  # maximum distance between two samples for one to be considered as in the neighborhood of the other
    min_samples = 2  # number of samples (or total weight) in a neighborhood for a point to be considered a core point

[event_matching]
evaluate = true

[visualization]
    evaluate = true
    drc = true
    video_instances = true
    plot_matching = true
    save_path = 'test.pdf'
    auto_open = false

[videos]
    path_to_videos = '/home/pl/projects/pl/MWT/data/videos/'
    video_ids = ["BW_MWT_191104_M1_R1", "BW_MWT_191104_M2_R2", "BW_MWT_191105_M1_R2", "BW_MWT_191105_M3_R3",
                 "BW_MWT_191107_M4_R2", "BW_MWT_191107_M5_R3", "BW_MWT_191104_M3_R1", "BW_MWT_191104_M1_R2",
                 "BW_MWT_191104_M2_R3", "BW_MWT_191105_M5_R2", "BW_MWT_191105_M6_R3", "BW_MWT_191104_M2_R1",
                 "BW_MWT_191104_M3_R2", "BW_MWT_191105_M2_R2", "BW_MWT_191105_M4_R2", "BW_MWT_191105_M5_R3",
                 "BW_MWT_191104_M5_R1", "BW_MWT_191104_M1_R3", "BW_MWT_191104_M6_R3", "BW_MWT_191105_M2_R3",
                 "BW_MWT_191107_M2_R2", "BW_MWT_191107_M3_R2", "BW_MWT_191107_M1_R3", "BW_MWT_191107_M2_R3"]
    dosage = '/home/pl/projects/pl/MWT/data/spreadsheets/06_20_2020_video_id_to_dose_virtual.xlsx'

[human_labels]
    summary_file = "/home/pl/projects/pl/MWT/data/spreadsheets/06_20_2020_SUMMARY_REPORT.xlsx"
    individual_files = ["/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200618_BW_1.xlsm",
                        "/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200618_BW_2.xlsm",
                        "/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200618_BW_3.xlsm",
                        "/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200618_BW_4.xlsm",
                        "/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200619_BW_1.xlsm",
                        "/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200619_BW_2.xlsm",
                        "/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200619_BW_3.xlsm",
                        "/home/pl/projects/pl/MWT/data/spreadsheets/MWTest_20200619_BW_4.xlsm"]

    blind_key_to_video_id = '/home/pl/projects/pl/MWT/data/human_video_label/blind.json'

    save_path = '/home/pl/projects/pl/MWT/results/{VIDEO_ID}.human.pkl'  # {VIDEO_ID} will be auto-replaced